{{ if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  labels:
    grafana_dashboard: "1"
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: serviceMetrics
      type: influxdb
      database: serviceMetricsDb
      user:
      password:
      access: proxy
    {{if .Values.serviceMetrics.external }}
      url: {{.Values.serviceMetrics.influxDbUrl}}
    {{else}}
      url: http://{{.Release.Name}}-influxdb.{{.Release.Namespace}}.svc.cluster.local:8086
    {{end}}
      isDefault: true
      tlsSkipVerify: true
      editable: true
{{ end }}