{{ if .Values.image.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.image.secretName}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}