apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}-secret
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  SSG_ADMIN_USERNAME: {{ .Values.management.username | b64enc }}
  SSG_ADMIN_PASSWORD: {{ .Values.management.password | b64enc }}
  SSG_CLUSTER_PASSWORD: {{.Values.clusterPassword | b64enc }}
{{ if .Values.tls.customDefaultSslKey.enabled }}
  SSG_SSL_KEY: {{ .Values.tls.customDefaultSslKey.key | b64enc }}
  SSG_SSL_KEY_PASS: {{ .Values.tls.customDefaultSslKey.pass | b64enc }}
{{ end }}
{{ if .Values.database.enabled }}
  SSG_DATABASE_USER: {{.Values.database.username | b64enc }}
  SSG_DATABASE_PASSWORD:  {{.Values.database.password | b64enc }}
{{ end }}
{{ if .Values.additionalSecret }}
{{- range $key, $val := .Values.additionalEnv }}
  {{ $key }}: "{{ $val | b64enc }}"
{{- end }}
{{ end }}

